version: '3'

services:
  formdang-sp-api:
    image: ${DOCKER_IMAGE_NAME}
    container_name: piece-spring
    ports:
      - "${PORT}:${PORT}"
    user: root
    privileged: true  # 이 부분을 추가합니다.ㅁ
    environment:
      - ACTIVE_PROFILE=${PROFILE}
    restart: unless-stopped