version: '3'

services:
  piece-spring:
    image: ${DOCKER_IMAGE_NAME}
    container_name: piece-spring
    ports:
      - "${PORT}:${PORT}"
    networks:
      - piece-network
    environment:
      - ACTIVE_PROFILE=${PROFILE}
    restart: unless-stopped

volumes:
  piece-network:
    external: true