version: '3'

services:
  piece-spring:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
      - "9201:9201"
    networks:
      - piece-network
    volumes:
      - logs:/logs
    environment:
      - ACTIVE_PROFILE=${PROFILE}
    restart: unless-stopped

networks:
  piece-network:
    external: true

volumes:
  logs:
    external: true